### ISSUE TITLE
Ngx capacitor http doesn't work on angular 14.1.0

### ISSUE THREAD

**Issue by jamalkarami** [sean-perkins/ngx-capacitor-http#2]
I have app built with anglular 14.1.0 and ionic 6, capacitor verion is  4.1

while installing ngxcapacitorhttp 
it signal somme error peerDependancies saying that 
ngxcapacotirhttp depend on angular@^6. and other 

I have lunched again with flag --legacy-peer-deps
Instalation is done;

I imported the NgxCapaticitor Module
I launched the ionic server, to test my app, and returned I unclair error : 

() => this.handleRequestError(e)

can you help me plaise

**Comment by sean-perkins** [comment]
The minimum Angular version target for the plugin is v13 of Angular. I will need a reproduction project to diagnose this issue.

**Comment by sean-perkins** [comment]
Closing as I didn't receive a reproduction. Please open a new issue with a reproduction if this issue effects you, thanks!
